<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="80" started-at="2019-11-08T14:29:57Z" finished-at="2019-11-08T14:29:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="80" started-at="2019-11-08T14:29:57Z" finished-at="2019-11-08T14:29:57Z">
      <class name="p1.Test1">
        <test-method status="PASS" signature="m2()[pri:0, instance:p1.Test1@1810399e]" name="m2" duration-ms="13" started-at="2019-11-08T14:29:57Z" finished-at="2019-11-08T14:29:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="FAIL" signature="m3()[pri:0, instance:p1.Test1@1810399e]" name="m3" duration-ms="3" started-at="2019-11-08T14:29:57Z" finished-at="2019-11-08T14:29:57Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at p1.Test1.m3(Test1.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m1()[pri:0, instance:p1.Test1@1810399e]" name="m1" duration-ms="9" started-at="2019-11-08T14:29:57Z" depends-on-methods="p1.Test1.m3" finished-at="2019-11-08T14:29:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
      </class> <!-- p1.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
