<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="138" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="138" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
      <class name="com.crm.qa.testcases.FirstTest">
        <test-method status="PASS" signature="Testing1()[pri:0, instance:com.crm.qa.testcases.FirstTest@91161c7]" name="Testing1" duration-ms="21" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testing1 -->
        <test-method status="PASS" signature="Testing2()[pri:0, instance:com.crm.qa.testcases.FirstTest@91161c7]" name="Testing2" duration-ms="7" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testing2 -->
        <test-method status="PASS" signature="Testing3()[pri:0, instance:com.crm.qa.testcases.FirstTest@91161c7]" name="Testing3" duration-ms="4" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testing3 -->
        <test-method status="PASS" signature="Testing4()[pri:0, instance:com.crm.qa.testcases.FirstTest@91161c7]" name="Testing4" duration-ms="2" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testing4 -->
        <test-method status="FAIL" signature="Testing5()[pri:0, instance:com.crm.qa.testcases.FirstTest@91161c7]" name="Testing5" duration-ms="16" started-at="2019-04-09T05:09:07Z" finished-at="2019-04-09T05:09:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.crm.qa.testcases.FirstTest.Testing5(FirstTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testing5 -->
      </class> <!-- com.crm.qa.testcases.FirstTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
