<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U94MBI6" ignored="2" name="Default test(failed)" tests="2" failures="2" timestamp="05 Apr 2020 06:47:01 GMT" time="0.07" errors="0">
  <testcase name="test3" time="0.015" classname="Retry_Failed_Test.Retry_Failed_Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Retry_Failed_Test.Retry_Failed_Test.test3(Retry_Failed_Test.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.003" classname="Retry_Failed_Test.Retry_Failed_Test">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Retry_Failed_Test.Retry_Failed_Test.test2(Retry_Failed_Test.java:19)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.0" classname="Retry_Failed_Test.Retry_Failed_Test">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test1" time="0.0" classname="Retry_Failed_Test.Retry_Failed_Test">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
